### PR TITLE
Xaiki/kill bootstrap

### PR DESCRIPTION
**Pull request by xaiki**
we want to kill bootstrap eventually.

### CODE REVIEW

**Comment by btzr-io** [comment]
Looks fine to me, we should probably remove all stuff we don't need anymore:

**Review by btzr-io — COMMENTED** [review]
Did you test / build this ( on butter-desktop app ) ?
Looks fine to me, we should probably remove all stuff (styles) we don't need anymore:

- [x] [styl/button.styl](https://github.com/buttercomponents/butter-component-builder/blob/xaiki/kill-bootstrap/styl/button.styl)
- [x] [styl/theme.styl](https://github.com/buttercomponents/butter-component-builder/blob/xaiki/kill-bootstrap/styl/theme.styl)

- [x] [styl/fonts.styl](https://github.com/buttercomponents/butter-component-builder/blob/xaiki/kill-bootstrap/styl/fonts.styl) 

It's done here -> #8

**Comment by xaiki** [comment]
button should die,
theme and fonts should be the default theme ? or do we have another way to depend on a default `
`butter-theme`now ?

**Comment by btzr-io** [comment]
Ok, we should implement `base-theme` before remove theme.

We don't use font.styl / button.styl:
https://github.com/buttercomponents/butter-component-builder/blob/master/styl/app.styl#L13
https://github.com/buttercomponents/butter-component-builder/blob/master/styl/app.styl#L16

**Comment by btzr-io** [comment]
https://github.com/buttercomponents/butter-component-builder/pull/8

**Pull request merged**
