### PR TITLE
package.json: update dependencies + bump version

### PR DESCRIPTION
**Pull request by z11h**
Since this is the base builder class with nothing reliant on it, updating deps is much easier.

Before starting to write a React Butter Component, I just wanted to make sure all the dependencies are up to date.

Cheers!

### CODE REVIEW

**Comment by xaiki** [comment]
you're updating babel and react to newer versions, they have breaking changes, did you check it doesn't break any existing component ?

**Comment by z11h** [comment]
I have not. Do any of them have travis CI testing them?

I've read through the React and Babel docs and none of them have breaking changes that would affect any of the Butter Components.

**Comment by xaiki** [comment]
please make sure our components still work as expected and reopen

**Comment by z11h** [comment]
@xaiki how can I test the existing components?

**Comment by xaiki** [comment]
clone their repo and look at them in a browser, that̀s a minimal first step until we get proper tests.

**Comment by btzr-io** [comment]
@xaiki should we close this? ( update ) -> https://github.com/buttercomponents/butter-component-builder/pull/7

**Comment by xaiki** [comment]
sure !

**Pull request closed without merging**
