### PR TITLE
Fix themes

### PR DESCRIPTION
**Pull request by btzr-io**
- [X] Remove `butter-installer-themes`

- [x]  Load themes from package.json ( devDependencies ).

### CODE REVIEW

**Comment by btzr-io** [comment]
Ok just to be sure how do I load them (properly in webpack) ?
``` JS
/node_modules\/(butter-theme-.*)\index.css/
```

**Comment by btzr-io** [comment]
> - Load themes from package.json ( devDependencies ).

#### Load all themes:
themes.js
``` JS

var pack = require('./package.json');

for(var theme in pack.devDependencies) {
    if(/(butter-theme-.*)/.test(theme)) {
        require(theme + '/index.css');
    }
}

```
webpack.config.js
``` JS
{
    entry: [
        path.join(__dirname, 'themes.js'),
        ...
    ],
    ...
}
```

**Comment by btzr-io** [comment]
@xaiki what you think? ^^
( I'll push the commits once you review it )

**Comment by xaiki** [comment]
looks good, i think you're missing your load themes code !

**Comment by btzr-io** [comment]
@xaiki What? Where?

**Comment by btzr-io** [comment]
> I'll push the commits once you review it 

Oh, like I said ^^

**Comment by btzr-io** [comment]
Can't fix settings CSS until we merge this ^^

**Pull request merged**
